from typing import Protocol, runtime_checkable


@runtime_checkable
class BatteryProtocol(Protocol):
    def is_battery_low_supported(self) -> bool: ...
    def is_battery_level_supported(self) -> bool: ...
    def battery_level(self) -> int | None: ...
    def battery_low(self) -> bool: ...
