from typing import Protocol, runtime_checkable


@runtime_checkable
class BatteryProtocol(Protocol):
    def is_battery_enabled(self) -> bool: ...
    def is_battery_level_value_enabled(self) -> bool: ...
    def battery_level_value(self) -> int | None: ...
    def low_battery(self) -> bool: ...
