from typing import Protocol, runtime_checkable


@runtime_checkable
class LockProtocol(Protocol):
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def is_locked(self) -> bool: ...
    def is_locking(self) -> bool: ...
    def is_unlocking(self) -> bool: ...
    def is_jammed(self) -> bool: ...
