from typing import Protocol, runtime_checkable


@runtime_checkable
class LockProtocol(Protocol):
    async def lock(self) -> None: ...
    async def unlock(self) -> None: ...
    async def open(self) -> None: ...
    async def close(self) -> None: ...

    def is_locked(self) -> bool: ...
    def is_locking(self) -> bool: ...
    def is_unlocking(self) -> bool: ...
    def openned(self) -> bool: ...
    def openning(self) -> bool: ...
    def closing(self) -> bool: ...
    def jammed(self) -> bool: ...

    def is_lock_supported(self) -> bool: ...
    def is_open_supported(self) -> bool: ...
    def is_jam_supported(self) -> bool: ...
