from typing import Protocol, runtime_checkable


@runtime_checkable
class LightProtocol(Protocol):
    async def turn_on(self) -> None: ...
    async def turn_off(self) -> None: ...
    async def set_level(self, level: int) -> None: ...
    def is_on(self) -> bool: ...
    def level(self) -> int | None: ...
    def is_level_supported(self) -> bool: ...
